[package]
name = "httpclient"
version = "0.0.1"
authors = ["Alessio Giambrone <AlessioGiambrone@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.0"
clap = "2.33.3"
json = "0.12.4"
regex = "1"
reqwest = { version = "0.11.4", features = ["blocking"] }
serde_json = "1.0.59"
